### ISSUE TITLE
incompatible network protocol 

### ISSUE THREAD

**Issue by Xellerate005** [thebigsmileXD/PocketRadio#22]
while trying to load the plugin with pmmp it camw with the error Could not load plugin 'PocketRadio': Incompatible network protocol version (plugin requires one of: 388) how do i fix this

**Comment by inxomnyaa** [comment]
I just updated the supported version, but for some reason i can not click buttons on Poggit right now..
And the builds are empty o.O
Until i fixed those issues on my side, try if you can get the latest dev build from here:
https://poggit.pmmp.io/ci/thebigsmileXD/PocketRadio/PocketRadio

**Comment by Xellerate005** [comment]
It won't let me

**Comment by Xellerate005** [comment]
Why don't you release it on github

**Comment by Xellerate005** [comment]
Is version 4.2.1 the right one

**Comment by inxomnyaa** [comment]
Yes thats the correct version.
I am having some issues with poggit still, maybe it also affects you too.. JQuery on poggit seems to be broken.
Releasing on github was initially not the plan because on poggit i can schedule an update and subscribed people know about it then, but i will try to upload a version as temporary solution
